GomocupOnline/Models/ResultTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GomocupOnline.Models
{
    public class ResultTable
    {
        public string Table { get; set;}
        public string FileName { get; set; }
    }
}

GomocupOnline/Controllers/EngineController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GomocupOnline.Controllers
{
    public class EngineController : Controller
    {
        //
        // GET: /Engine/
        public ActionResult Download(string engine)
        {
            TournamentController.SecurityCheckPath(engine);

            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "AI");

            string[] possibleformat = new string[]
            {
                engine + ".zip",
                "pbrain-" + engine + ".zip",
                 engine + ".exe",
                "pbrain-" + engine + ".exe",
            };

            foreach (string item in possibleformat)
            {
                string fullpath = Path.Combine(path, item);
                if (!System.IO.File.Exists(fullpath))
                    continue;

                //counter
                string counterFile = fullpath + ".counter";
                int downloadedCount = 0;
                if (System.IO.File.Exists(counterFile))
                {
                    string strCounter = System.IO.File.ReadAllText(counterFile);
                    int.TryParse(strCounter, out downloadedCount);
                }
                downloadedCount++;
                System.IO.File.WriteAllText(counterFile, downloadedCount.ToString());

                return DownloadBinary(fullpath);
            }

            return new HttpStatusCodeResult(404);
        }

        public FileResult DownloadBinary(string path)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
	}
}

GomocupOnline/Controllers/TournamentController.cs
using GomocupOnline.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GomocupOnline.Controllers
{
    public class TournamentController : Controller
    {

        public ActionResult Schedule()
        {
            return View();
        }

        public ActionResult Openings()
        {
            return View();
        }

        public ActionResult OpeningsImg()
        {
            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "openings.png");
            Response.ContentType = "image/png";

            return DownloadBinary(path);
        }

        public FileResult DownloadBinary(string path)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult OpeningsDownload()
        {
            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "openings.txt");

            return DownloadBinary(path);
        }

        public ActionResult Results()
        {
            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "Tournaments");

            if (!Directory.Exists(path))
                return View(new TournamentModel[0]);

            string[] dirs = Directory.GetDirectories(path);

            TournamentModel[] model = dirs.Select(d => new TournamentModel(d)).ToArray();
            return View(model);
        }

        public ActionResult MatchesByEngine(string tournament, string engine)
        {
            if (tournament == null || tournament.Contains("."))
                throw new ArgumentException();

            GomokuMatchInfoModel[] matches = GetMatchesModelByTournament(tournament);

            matches = matches
                .Where(m => m.Player1 == engine || m.Player2 == engine)
                .ToArray();

            TournamentMatch model = new TournamentMatch()
            {
                Matches = matches,
                Tournament = tournament,
            };

            return View("Matches", model);
        }

        public ActionResult Matches(string tournament)
        {
            if (tournament == null || tournament.Contains("."))
                throw new ArgumentException();

            GomokuMatchInfoModel[] matches = GetMatchesModelByTournament(tournament);

            TournamentMatch model = new TournamentMatch()
            {
                Matches = matches,
                Tournament = tournament,
            };

            return View(model);
        }

        private static GomokuMatchModel[] GetMatchesByTournament(string tournament)
        {
            SecurityCheckPath(tournament);

            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "Tournaments");
            path = Path.Combine(path, tournament);

            string[] files = Directory.GetFiles(path, "*.psq");

            GomokuMatchModel[] model = new GomokuMatchModel[files.Length];

            for (int i = 0; i < files.Length; i++)
            {
                model[i] = new GomokuMatchModel(files[i]);
            }
            return model;
        }

        private static GomokuMatchInfoModel[] GetMatchesModelByTournament(string tournament)
        {
            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "Tournaments");
            path = Path.Combine(path, tournament);

            string[] files = Directory.GetFiles(path, "*.psq");

            GomokuMatchInfoModel[] model = new GomokuMatchInfoModel[files.Length];

            for (int i = 0; i < files.Length; i++)
            {
                string file = files[i];
                GomokuMatchModel matchModel = new GomokuMatchModel(file);


                model[i] = new GomokuMatchInfoModel()
                {
                    FileName = tournament + "\\" + Path.GetFileName(file),
                    LastChange = new FileInfo(file).LastWriteTime,
                    Player1 = matchModel.Player1,
                    Player2 = matchModel.Player2,
                    Moves = matchModel.Moves.Length,
                    Result = matchModel.GetMatchResult(),
                };
            }
            return model;
        }

        public ActionResult Compare(string engine, string tournamentMatch)
        {
            SecurityCheckPath(tournamentMatch);

            string tournament = Path.GetDirectoryName(tournamentMatch);

            string path = GetMatchPath(tournamentMatch);
            GomokuMatchModel reference = new GomokuMatchModel(path);
            reference.FileName = tournamentMatch.Replace("\\", "\\\\");


            GomokuMatchModel[] sameOpening = GetMatchesWithSameOpening(reference, tournament, engine);

            GomokuCompareModel model = new GomokuCompareModel()
            {
                Matches = sameOpening,
                Reference = reference,
                Player = engine,
            };

            return View(model);
        }

        private GomokuMatchModel[] GetMatchesWithSameOpening(GomokuMatchModel reference, string tournament, string engine)
        {
            int minMoves = 3;

            if (reference.Moves.Length < minMoves)
                return new GomokuMatchModel[0];


            GomokuMatchModel[] all = GetMatchesByTournament(tournament);

            List<GomokuMatchModel> selection = new List<GomokuMatchModel>();

            foreach (GomokuMatchModel item in all)
            {
                if (item.Moves.Length < minMoves)
                    continue;

                if (reference.FileName.EndsWith(item.FileName))
                    continue;//self

                int maxMoves = Math.Min(item.Moves.Length, reference.Moves.Length);

                //if( reference.Player1 == player)
                //{
                //    if (item.Player1 == reference.Player1)
                //        continue;//self
                //}
                //else if (reference.Player2 == player)
                //{
                //    if (item.Player2 == reference.Player1)
                //        continue;//self
                //}

                bool founded = true;

                for (int i = 0; i < maxMoves; i++)
                {
                    if ((item.Moves[i].X != reference.Moves[i].X) || (item.Moves[i].Y != reference.Moves[i].Y))
                    {
                        if (i % 2 == 1 && engine == reference.Player2 && i > minMoves)
                        {
                            founded = true;
                            break;
                        }

                        if (i % 2 == 0 && engine == reference.Player1 && i > minMoves)
                        {
                            founded = true;
                            break;
                        }
                        founded = false;
                        break;
                    }
                }
                if (founded)
                {
                    selection.Add(item);
                }
            }

            return selection.ToArray();
        }

        public ActionResult Match(string tournamentMatch)
        {
            SecurityCheckPath(tournamentMatch);

            string path = GetMatchPath(tournamentMatch);
            GomokuMatchModel model = new GomokuMatchModel(path);
            model.FileName = tournamentMatch.Replace("\\", "\\\\");
            return View(model);
        }

        public static void SecurityCheckPath(string tournamentMatch)
        {
            if (tournamentMatch == null || tournamentMatch.Contains("..") || tournamentMatch.Contains(":"))
                throw new ArgumentException();
        }

        public JsonResult MatchJSON(string tournamentMatch)
        {
            SecurityCheckPath(tournamentMatch);

            string path = GetMatchPath(tournamentMatch);
            GomokuMatchModel model = new GomokuMatchModel(path);
            model.FileName = tournamentMatch.Replace("\\", "\\\"");
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public static string GetMatchPath(string tournamentMatch)
        {
            SecurityCheckPath(tournamentMatch);

            string path = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            path = Path.Combine(path, "Tournaments");
            path += "\\" + tournamentMatch;
            return path;
        }

    }
}

GomocupOnline/Views/Tournament/Compare.cshtml
@using System.Linq
@using GomocupOnline.Models

@model GomokuCompareModel

@{
    ViewBag.Title = "Compare " + Model.Player;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table>
    @foreach (var item in Model.Matches)
    {
        {
            //last move index, when the matches are same
            int diffSeparator = 0;

            int min = Math.Min(Model.Reference.Moves.Length, item.Moves.Length);
            for (int i = 0; i < min; i++)
            {
                var moveRef = Model.Reference.Moves[i];
                var moveItem = item.Moves[i];
                if (moveItem.X == moveRef.X && moveItem.Y == moveRef.Y)
                {
                    diffSeparator = i;
                }
                else
                {
                    break;
                }
            }

            Model.Reference.DiffSeparator = diffSeparator;
            item.DiffSeparator = diffSeparator;
        }
        <tr>
            <td colspan="2" style="text-align:center">
                <br /><br />
                <h3>
                    @Model.Player
                    vs
                    @(Model.Player == Model.Reference.Player1 ? item.Player1 : item.Player2)
                </h3>
            </td>
        </tr>
        <tr>
            <td>@Html.Partial("MatchPartial", Model.Reference)</td>
            <td>@Html.Partial("MatchPartial", item)</td>

        </tr>
    }
</table>


@section scripts {
    <script type="text/javascript" src="~/Scripts/gomoku.replay.js"></script>
}

GomocupOnline/Views/Tournament/Match.cshtml
@model GomocupOnline.Models.GomokuMatchModel

@{
    ViewBag.Title = Model.Player1 + " vs " + Model.Player2;
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@ViewBag.Title</h2>

@Html.Partial("MatchPartial", Model)
<br />
<br />

@Html.ActionLink("Download " + Model.Player1, "Download", "Engine", new { engine = Model.Player1 }, null)
<br />
@Html.ActionLink("Download " + Model.Player2, "Download", "Engine", new { engine = Model.Player2 }, null)
<br />
@Html.ActionLink("Compare " + Model.Player1 + " match with other engines", "Compare", "Tournament", new { engine = Model.Player1, tournamentMatch = Model.FileName }, null)
<br />
@Html.ActionLink("Compare " + Model.Player2 + " match with other engines", "Compare", "Tournament", new { engine = Model.Player2, tournamentMatch = Model.FileName }, null)



@section scripts {
    <script type="text/javascript" src="~/Scripts/gomoku.replay.js"></script>
}


GomocupOnline/Views/Tournament/Matches.cshtml
@using System.Linq
@using GomocupOnline.Models

@model TournamentMatch


@{
    ViewBag.Title = "Matches";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var strongStart = "<strong>";
    var strongEnd = "</strong>";

    string[] players1 = Model.Matches.Select(match => match.Player1).Distinct().ToArray();
    string[] players2 = Model.Matches.Select(match => match.Player2).Distinct().ToArray();
    List<string> playersBoth = new List<string>();
    playersBoth.AddRange(players1);
    playersBoth.AddRange(players2);
    string[] players = playersBoth.Distinct().ToArray();
}

<h2>Engines</h2>

@foreach (string engine in players)
{
    @Html.ActionLink(engine, "MatchesByEngine", "Tournament", new { engine = engine, tournament = Model.Tournament }, null)
    <text>,</text>
}
    

<h2>Matches</h2>

<table class="table">
    <tr>
        <th>
            LastChange
        </th>
        <th>
            FileName
        </th>
        <th>
            Player 1
        </th>
        <th>
            Player 2
        </th>
        <th>
            Moves
        </th>
        <th>
            Detail
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Matches)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastChange)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @if (item.Result == 1)
                {
                    @Html.Raw(strongStart)
                }
                @Html.DisplayFor(modelItem => item.Player1)
                @if (item.Result == 1)
                { 
                    @Html.Raw(strongEnd)
                }
            </td>
            <td>
                @if (item.Result == -1)
                {
                    @Html.Raw(strongStart)
                }
                @Html.DisplayFor(modelItem => item.Player2)
                @if (item.Result == -1)
                {
                    @Html.Raw(strongEnd)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moves)
            </td>
            <td>
                @Html.ActionLink("Detail", "Match", new { tournamentMatch = item.FileName })
            </td>
        </tr>
    }

</table>

GomocupOnline/Views/Tournament/Openings.cshtml

@model string

@{
    ViewBag.Title = "Openings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Openings</h2>

<img src="@Url.Action("OpeningsImg", "Tournament")" />

<br /><br />

@Html.ActionLink("Download", "OpeningsDownload", "Tournament")

GomocupOnline/Views/Tournament/Results.cshtml
@model IEnumerable<GomocupOnline.Models.TournamentModel>

@{
    ViewBag.Title = "Tournaments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            List
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Matches", "Matches", new { Tournament = item.Title })            
        </td>
    </tr>
}

</table>

GomocupOnline/Views/Tournament/Schedule.cshtml
@{
    ViewBag.Title = "Schedule 2015";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Gomocup Schedule 2015, 1st-3rd of May 2015</h1>

<p>
    There will be 3 freestyle groups in Tournament 2015.
</p>


<h3> Friday morning</h3>

<ul>
    <li>3rd Freestyle 3 league - starts On Friday 2015 at 12:00 UTC/GMT time</li>
</ul>

<h3>Friday afternoon</h3>

<ul>
    <li>2nd Freestyle gomoku league</li>
    <li>Fastgame</li>
</ul>

<h3>Saturday 7:30 (Standard time zone UTC/GMT ) = 8:30 (Daylight saving time UTC/GMT)</h3>
<ul>
    <li>Standard gomoku league</li>
</ul>

<h3>Saturday 17:00(Standard time zone UTC/GMT ) = 18:00 (Daylight saving time UTC/GMT)</h3>

<ul>
    <li>1nd Freestyle gomoku league</li>
</ul>

<h3>Sunday</h3>

<ul>
    <li>Collecting results</li>
</ul>

<h3>What is new?</h3>

<h4>Updates</h4>
<ul>
    <li>Goro 2015 - quite different</li>
    <li>Hewer 2015 - faster, more strategic</li>
    <li>SlowRenju 2015 - improvement of searching algorithms and parameters</li>
    <li>Swine 2015 - more correct algorithm</li>
    <li>Kanec 2015 - not confirmed because of crashing - waiting for fixing the problem</li>
    <li>Yixin 2015 - algorithm has been improved and a bug has been fixed</li>
    <li>Zetor 2015 - bugs fixed</li>
    <li>Imro 2015 - improoved</li>
</ul>

<h4>New AI</h4>
<ul>
    <li>AcePela2 - open source AI based on Pela, source code and modifications are inlcuded</li>
    <li>XoXo15</li>
</ul>

<h4>Ranking 2014</h4>

<ol>
    <li>YIXIN2014</li>
    <li>RENJUSOLVER</li>
    <li>HEWER2014</li>
    <li>TITO2014</li>
    <li>SWINE2014</li>
    <li>HGARDEN07</li>
    <li>GORO2014</li>
    <li>PELA</li>
    <li>GMOTOR11</li>

    <li>SLOWRENJU2014</li>
    <li>KANEC</li>
    <li>HIGHFIVE</li>
    <li>JUDE</li>
    <li>AMOEBA10</li>
    <li>ZETOR</li>
    <li>QMENTAT6</li>
    <li>PECUCHET</li>
    <li>NOESIS</li>
    <li>NABAMOKU</li>

    <li>PUSKVOREC</li>
    <li>PUREGM12</li>
    <li>LICHT14</li>
    <li>FAST-GOMOKU14</li>
    <li>PISQ7</li>
    <li>IMRO13</li>
    <li>FIVEROW</li>
    <li>PROLOG</li>
    <li>BENJAMIN</li>
    <li>VALKYRIE</li>
    <li>CRUSHER10</li>
    <li>MUSHROOM</li>   																						
</ol>

GomocupOnline/Views/Tournament/Tournaments.cshtml
@model IEnumerable<GomocupOnline.Models.TournamentModel>

@{
    ViewBag.Title = "Tournaments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            List
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Matches", "Matches", new { Tournament = item.Title })            
        </td>
    </tr>
}

</table>